---
title: "analysis"
output: html_document
---

```{r}
adhd = read.csv("C:/Users/yagmu/Desktop/Auburn/Research/project/datasetADHD/train_data.csv")
adhd = t(adhd)
colnames(adhd) = as.character(adhd[2,])
adhd = adhd[-(1:2),]
X = apply(adhd[,-1], 2, as.numeric)
adhd = data.frame(adhd[,1], X)
adhd = as.data.frame(adhd)

rownames(adhd) = 1:nrow(adhd)

adhd[adhd == "Controls"]=0
adhd[adhd == "ADHD-C" | adhd == "ADHD-H" | adhd == "ADHD-I"]=1

predictors = as.data.frame(adhd[,-1])
y = as.factor(adhd[,1])

set.seed(2794) 
ind = sample(1:dim(predictors)[1],dim(predictors)[1]*0.2)  
y_test = y[ind]
y_train = y[-ind]
x_test = predictors[ind,]
x_train = predictors[-ind,]

```


```{r message=FALSE, warning=FALSE}
load("C:/Users/yagmu/Desktop/padmini/ADHD_package.Rda")

min_error = min(train_swag_svml$cv_alpha)


varmat_ind = list() #saves the varmat index from CV errors
for(i in 1:20){
  varmat_ind[[i]]=which(train_swag_svml$CVs[[i]]<=min_error, arr.ind = T)
}

post_sel = list() # models selected after post-processing
for(i in 1:20){
  post_sel[[i]] = train_swag_svml$VarMat[[i]][,varmat_ind[[i]]]
}

post_sel[[1]] = t(as.matrix(post_sel[[1]]))

for(i in 1:20){
  if(!is.matrix(post_sel[[i]])){
    post_sel[[i]]=t(as.matrix(post_sel[[i]]))
  }
}

post_sel[[9]] = t(post_sel[[9]])


x = c() #non-empty elements of post-group
for(i in 1:20){
  if(length(post_sel[[i]])!=0){
    x = c(x,i)
  }
  x = x
}

for(i in 1:length(x)){
  if(nrow(post_sel[[x[i]]])<20){
    diff = 20 - nrow(post_sel[[x[i]]])
    post_sel[[x[i]]] = rbind(post_sel[[x[i]]],matrix(NA,nrow = diff, ncol = ncol(post_sel[[x[i]]])))
  } 
}


models = matrix(NA, nrow = 20,ncol=ncol(post_sel[[x[1]]]))

models[1:nrow(post_sel[[x[1]]]),]=post_sel[[x[1]]]

for(i in 2:length(x)){
  models = cbind(models,post_sel[[x[i]]])
}

models = t(models)

selected_var = c() 
for(i in 1:ncol(models)){
  selected_var = c(selected_var,models[,i])
}
selected_var = na.omit(unique(selected_var))
selected_var = sort(selected_var)
#colnames(x_train)[selected_var]
#table(models)

```

|-|Variable      | Frequency| 
|-| -------------- | ------- |
| 1| 13,11      | 51|
| 2|  27,21      | 51|
| 3|    40,19  | 3|
| 4|   47,9  | 5|
| 5|   47,21| 258|
| 6|  47,27| 1|
| 7|  49,9| 3|
| 8|   49,47| 21|
| 9|  54,21      | 381|
| 10|  72,11    | 363|
| 11|  72,68  | 381|
| 12| 74,21  | 43|
| 13|  74,55| 63|
|14|82,13| 12|
|15|85,13| 8|
|16|101,85| 381|
|17| 104,34      | 377|
|18| 108,27      | 207|
| 19|108,47  | 73|
| 20|108,91  | 201|
| 21|112,67| 7|
|22| 114,6| 23|
|23| 114,28| 172|
|24| 114,40| 281|
|25| 116,21      | 45|
| 26| 116,47      | 23|
| 27| 116,55  | 84|
| 28| 116,89  | 381|
|29|  124,23| 28|
|30| 124,99| 284|
|31| 126,2| 325|
|32| 126,124| 18|
| 33| 129,40      | 25|
|34|  132,85      | 1|
|35| 134,23  | 46|
|36| 134,99  | 66|
|37|  135,114| 1|
|38| 136,132| 1|
|39| 138,23| 20|
|40| 138,107| 9|
|41| 146,89      | 235|
|42|  148,71      | 9|
|43|  150,114  | 363|
|44|  151,46  | 55|
|45|  151,147| 377|
|46| 162,73| 267|
|47| 169,49| 34|
|48| 173,9| 149|
|49|  173,47      | 13|
|50|  184,58      | 37|
|51|  189,21  | 1|
|52|  189,65  | 7|
|53|  189,173| 37|

```{r message=FALSE, warning=FALSE}
require(plotrix)

m_vector <- sapply(train_swag_svml$CVs, function(x) summary(x)[4])

l_vector <- sapply(train_swag_svml$CVs, function(x) summary(x)[1])

u_vector <- sapply(train_swag_svml$CVs, function(x) summary(x)[6])

plotCI(1:length(train_swag_svml$CVs), m_vector, ui=u_vector, li=l_vector, scol = "grey", col="red", pch = 16, main = "Ranges 10-fold CV Misclassification Errors",ylab = "Range CV Error",xlab = "Model Size")
```

```{r}
betas = matrix(NA, ncol=ncol(models), nrow=nrow(models))
for(i in 1:nrow(models)){
  ind_models = models[i,]
  ind_models = unlist(na.omit(ind_models))
  data = as.data.frame(cbind(y_train, x_train[,ind_models]))
  names(data) = c("y_train", names(x_train[,ind_models]))
  betas[i,1:length(ind_models)]=glm(y_train~ ., data = data, family = "binomial")$coefficients[-1]
}


sign_betas = list()
for(i in 1:length(selected_var)){
  sign_betas[[i]] = betas[which(models==selected_var[i],arr.ind = T)]
}

corr = matrix(NA, nrow = length(selected_var), ncol = length(selected_var))
for(i in 1:length(selected_var)){
  for(j in 1:length(selected_var)){
    corr[i,j] = cor(x_train[,selected_var[i]],x_train[,selected_var[j]], method = "spearman")
  }
}
colnames(corr) = colnames(x_train)[selected_var]
rownames(corr) = colnames(x_train)[selected_var]



A = matrix(0, nrow = ncol(models), ncol =ncol(models))
intensity = matrix(0, nrow = length(selected_var), ncol = length(selected_var))
b=0
a = list()
for(i in 1:(length(selected_var)-1)){
  for(j in (i+1):length(selected_var)){
    for(k in 1:(ncol(models)-1)){
      a[[i]]=which(models[,k]==selected_var[i])
      for(n in (k+1):(ncol(models))){
        A[k,n]=length(which(models[a[[i]],n]==selected_var[j]))
      }
    }
    intensity[i,j]=sum(A)
    intensity[j,i]=sum(A)
  }
}

#variables that are mostly together
which(intensity==max(intensity),arr.ind = T)
```

# Creating network
```{r message=FALSE, warning=FALSE}
#required packages
library(igraph)
library(dplyr)
library(gdata)
#creating adjacency matrix
adjacency_matrix = matrix(NA, ncol = ncol(intensity), nrow = nrow(intensity))

for(i in 1:ncol(adjacency_matrix)){
  for(j in 1:nrow(adjacency_matrix)){
    if(intensity[i,j]>0){
      adjacency_matrix[i,j]=1
    }else{
      adjacency_matrix[i,j]=0
    }
  }
}

graph = graph.adjacency(adjacency_matrix, mode = 'undirected')

# colors of vertices 
beta_sign = rep(NA,53)
for(i in 1:length(beta_sign)){
  if(sign_betas[[i]]>0){
    beta_sign[i] = 1
  }else{
    beta_sign[i] = -1
  }
}

colrs = rep(NA, 53)
for(i in 1:length(colrs)){
  if(beta_sign[[i]]>0){
    colrs[i] = "lightblue"
  }else{
    colrs[i] = "tomato"
  }
}

# size of vertices
 a = table(models)
V(graph)$size = a*0.05

V(graph)$label = c(1:53)

# edge thickness
upper_thick = upperTriangle(intensity, byrow = T)
upper_thick = upper_thick[upper_thick!=0]
E(graph)$width = upper_thick*0.01

#edge colors
colrs_edge = rep(NA, 1000)
for(i in 1:length(colrs_edge)){
  if(upper_thick[i]>0){
    colrs_edge[i]="lightgreen"
  }else{
    colrs_edge[i]="lightpink"
  }
}


#plotting the network
plot(as.undirected(graph), vertex.color=colrs, vertex.label.size = V(graph)$size, vertex.label=V(graph)$label, edge.width = E(graph)$width, edge.color="grey", layout= layout_randomly)



```

#coloring the vertices according to pos/neg effect
#V(graph)$name = colnames(x_train)[selected_var]

#V(graph)$effect = beta_sign
#V(graph)$color = colrs[V(graph)$effect]
